### ISSUE TITLE
Option to select Online or Offline

### ISSUE THREAD

**Issue by ashwitag** [dayschedule/public-roadmap#14]
Hello, 

I'd like to request a feature to allow the client to choose a session, followed by whether the client wants to join online or offline, and for them to receive the joining link/ physical address appropriately. Because all my sessions are available as online as well as offline, for personal and group events, so it helps to not have to clone all events as online and offline separately. 

Thanks.

**Comment by vickyrathee** [comment]
The multiple location feature has been accepted and starting working on it. Once this feature is released, the event owner will be able to select multiple locations.

And, the invitee can select any of them while registration to confirm their booking on selected [online or offline location for an event](https://dayschedule.com/docs/t/locations/273).

**Comment by vickyrathee** [comment]
Feature shipped, you can now add multiple location to let customers choose

https://dayschedule.com/docs/change-log

![image](https://user-images.githubusercontent.com/6106479/177767272-f9bfda7e-c994-485c-b65c-642aee64a289.png)
