### ISSUE TITLE
Feature Request  | Greyout the dates when it is fully booked and enable only on cancellation/Reschedule

### ISSUE THREAD

**Issue by ar14jun** [dayschedule/public-roadmap#16]
Hi Team,

Can the dates be blurred/greyed or even show as not available when the those dates are completely booked.

We could notice that when the user tries from mobile to book, it shows as available, however no time slots are show (since they have already been booked). User mentions that it a hassle to use from the mobile as the page goes back to the very 1st page (planning page to select event again). 

Happy to explain in detail if needed over a call/session.

Regards,
Sumithra

**Comment by vickyrathee** [comment]
@ar14jun thanks for reporting, we are working on this to implement a fix around next week.

**Comment by vickyrathee** [comment]
This is fixed in today's release

https://dayschedule.com/docs/change-log
