### ISSUE TITLE
please add the answer of the meeting in calendar description.

### ISSUE THREAD

**Issue by timothy-wct** [dayschedule/public-roadmap#17]
only the answered question will be added

if blank, please skip it

**Comment by vickyrathee** [comment]
This feature is shipped now- The [day schedule](https://dayschedule.com/) app will add all the invitee questions in calendar along with other details like event name, time etc.

![Appointment registration questions](https://user-images.githubusercontent.com/6106479/165040544-250155ea-4e28-43eb-b7ca-3fae0fb9b9c6.png)

- For example, the following event registration will be converted into above [Google calendar meeting](https://dayschedule.com/docs/t/how-to-use-google-calendar-for-appointments/338).

![Dynamic event registration form with appointment scheduling sofware](https://user-images.githubusercontent.com/6106479/165040496-3c0b648e-70b6-4d39-88e2-ffb8c41af310.png)
