### ISSUE TITLE
Independent option for  the timeframe can be choose (instead of defined by the duration of the meeting)

### ISSUE THREAD

**Issue by timothy-wct** [dayschedule/public-roadmap#18]
e.g. 60 mins meeting can be booked every 30 mins(13:00, 13:30, 14:00, 14:30, 15:00)

**Comment by vickyrathee** [comment]
The duration is used to display slots. For example, 
- A 30 minutes meeting duration will show 9:00, 9:30, 10:00, 10:30 etc.
- While a 60 minutes meeting will show 9:00, 10:00, 11:00 etc.

So, this is something not a priority for us right now. But we re-review if getting upvotes or likes in this thread from other customers as well.

**Comment by Lifeischoice** [comment]
This should really be a no brainer and needs to be prioritized. No business wants to have their appointment scheduler be the cause of loosing money. Imagine you have 60 minutes meetings (9:00, 10:00, etc) and a client have availabilty to book with you  starting at 9:30? Now missed opportunity. The is a critical time management issue shortcoming for DaySchedule. Time is money they say and loosing opportunity to serve your clients because your appointment scheduler is not flexible enough to accomodate 30 minutes or even 15 minutes  increment slots is not efficient. Please reconsider and update the algorithm sooner than later.

**Comment by timothy-wct** [comment]
> This should really be a no brainer and needs to be prioritized. No business wants to have their appointment scheduler be the cause of loosing money. Imagine you have 60 minutes meetings (9:00, 10:00, etc) and a client have availabilty to book with you starting at 9:30? Now missed opportunity. The is a critical time management issue shortcoming for DaySchedule. Time is money they say and loosing opportunity to serve your clients because your appointment scheduler is not flexible enough to accomodate 30 minutes or even 15 minutes increment slots is not efficient. Please reconsider and update the algorithm sooner rather than later.

totally agree! could support team really consider this??

**Comment by TheGeekosaurus** [comment]
> This should really be a no brainer and needs to be prioritized. No business wants to have their appointment scheduler be the cause of loosing money. Imagine you have 60 minutes meetings (9:00, 10:00, etc) and a client have availabilty to book with you starting at 9:30? Now missed opportunity. The is a critical time management issue shortcoming for DaySchedule. Time is money they say and loosing opportunity to serve your clients because your appointment scheduler is not flexible enough to accomodate 30 minutes or even 15 minutes increment slots is not efficient. Please reconsider and update the algorithm sooner rather than later.

This is the only reason that brought me to take a look at the roadmap. 
There should be a 10-15 minutes interval max between available slots if there are no times booked at the moment, regardless of the event duration.
Then once a time is booked, the system makes the math of the event duration + buffers to block the other slots.
This is indeed a priority!

**Comment by TheGeekosaurus** [comment]
Any estimated ETA on this? 
I just can't use the software as far as this option is not available.

**Comment by vickyRathee** [comment]
October - November 2022

**Comment by timothy-wct** [comment]
Is that implementing?

在 2022年9月27日週二 11:23，Vikash Rathee ***@***.***> 寫道：

**Comment by vickyRathee** [comment]
@timothy-wct  this feature is under testing and delayed for December 2022

**Comment by vickyRathee** [comment]
This feature has been released now on [DaySchedule](https://dayschedule.com/)

- You can set the minutes/hours to generate slots based on the provided value

![Independent time slots](https://user-images.githubusercontent.com/6106479/230890571-e119f47e-c5d5-4eda-a537-056004eee58d.png)
