### ISSUE TITLE
Showing price along with the service

### ISSUE THREAD

**Issue by ashwitag** [dayschedule/public-roadmap#20]
I just noticed today that price shows up only in the very end. Is it please possible to show the price in the initial phase itself so that the client has more clarity?

**Comment by vickyrathee** [comment]
Do you mean on top of booking page?

**Comment by ashwitag** [comment]
Yes, like this for example... helps clients who are low on funds to quickly
decide what to book.

[image: image.png]

**Comment by vickyrathee** [comment]
Yes, we accepted this feature and will be shipped later today.
This is how the price will looks like on paid events -

![image](https://user-images.githubusercontent.com/6106479/165232585-9de08ae8-6120-4d16-8e3c-6fe18aec51c3.png)

**Comment by vickyrathee** [comment]
This feature is shipped now - 

https://dayschedule.com/docs/change-log
