### ISSUE TITLE
Semi Customized event topic in google calendar

### ISSUE THREAD

**Issue by timothy-wct** [dayschedule/public-roadmap#21]
instead of always showing the participant and myself
is it possible for us to set each event display name in google calendar?

**Comment by vickyrathee** [comment]
The invitee name and host name is used in calendar title by default. Do you want to use event name instead? That will seems duplicate as each entry will use the same event name

![image](https://user-images.githubusercontent.com/6106479/164980098-2f927b0e-bf2d-4a2d-95f7-0bd90adb8036.png)

**Comment by timothy-wct** [comment]
i would like to have [invitee name]&Event name, instead of the host name
just ask to see if this can be added~thanks for your reply

**Comment by vickyrathee** [comment]
This feature is shipped today. The Invitee name and event name is used to add in calendar now https://dayschedule.com/docs/change-log

![image](https://user-images.githubusercontent.com/6106479/165041468-a4e98fb8-cee2-48a9-beda-f1abff8788d8.png)

**Comment by timothy-wct** [comment]
why the name change to booking confirmed: xxxxxxxxxxxxxxxxxxx {time} now??
