### ISSUE TITLE
Why sms is not reaching to the person who books appointment?

### ISSUE THREAD

**Issue by RuchitaMaheshwari** [dayschedule/public-roadmap#24]
In sms feature I am receiving all messages on sms but the opposite invitee is not getting any sms this is a bid trouble needs solution or fix this bug urgently.

**Comment by vickyrathee** [comment]
Check the workflow history to find the status to ensure the number if valid, no other errors
- Keep the message short (Maximum: 160 char)
- No bold, italic, hyperlinks etc.

![SMS reminder on appointment schedule](https://user-images.githubusercontent.com/6106479/165744151-d98f1fed-8821-4ed0-9f05-f2fc2fe33f5d.png)

We've just tested with 4 different mobile numbers and there are no issue found on any of them!

![Meeting reminder on SMS](https://user-images.githubusercontent.com/6106479/165744581-83bd6f21-d6c3-421d-be7e-ac05f290ee0c.png)
