### ISSUE TITLE
Can you add event rescheduled 

### ISSUE THREAD

**Issue by RuchitaMaheshwari** [dayschedule/public-roadmap#25]
Hello can you please add sms and whstapp notification box when we are rescheduling any appointment 

![Screenshot (154)](https://user-images.githubusercontent.com/104567704/165943743-1aa809c4-0bf5-4d27-b033-ce0161dc3d15.png)

**Comment by vickyRathee** [comment]
The `event_rescheduled` workflow is available now https://dayschedule.com/docs/change-log to setup any actions like SMS to trigger when an event is rescheduled.

![image](https://github.com/user-attachments/assets/5b22e820-2d27-4c51-a7ca-aa83623a57c8)
