### ISSUE TITLE
Feature Request: Indicating 'No Slots Available'

### ISSUE THREAD

**Issue by ashwitag** [dayschedule/public-roadmap#29]
Hello, 

At the moment when no slots are available, the right side shows as blank. This is confusing my clients. If a text can be shown on the right saying something to the effect of 'No slots available on this date, please try another day' - or something like that, it'll make the process more intuitive.

**Comment by vickyrathee** [comment]
This feature has been shipped - https://dayschedule.com/docs/change-log

![dayschedule calendar scheduling software](https://user-images.githubusercontent.com/6106479/168773488-d3e5b8ce-71e0-4354-8ca1-c8c24df7ce6c.png)
