### ISSUE TITLE
Feature request - invitees detail excel download

### ISSUE THREAD

**Issue by Rashidkallur** [dayschedule/public-roadmap#3]
Hi,, I loved your features.
I have a suggestion that will be very useful.
The invitees registration in webinar/event booking category must be a downloadable one in excel format. So that we can get all invitees details in a one click,, (as the option available in razorpay and Google form etc)

**Comment by vickyrathee** [comment]
@Rashidkallur The invitees downloads feature is already available on [/bookings](https://app.dayschedule.com/bookings) page. I just re-checked and it's working fine. Can you please provide more details if I am missing anything?

Here are the docs - https://dayschedule.com/docs/t/how-to-download-booking-invitees-registration-data-in-excel/305

**Comment by Rashidkallur** [comment]
What I meant is...
Let me describe a situation..
For example, I created an event and many got registered in it. So there's a
list of invitees in a single event.. so how can I get the list of those
invitees & their entered details?

And I think it will be great if you develop an app for mobiles too

**Comment by vickyrathee** [comment]
We'll considering this feature to be added in this month. When done, you will be able to download single event invitees and their questions/answers.

Having said that, @Rashidkallur you may still use the download option to [download all the data](https://dayschedule.com/docs/t/how-to-create-a-private-vaccine-appointment-booking-system-for-your-hospital/306#Download_registration_data) related to all events, invitees and their entered questions. Then just filter by event in the downloaded spreadsheet.

The mobile app development is already in plan for around end of the year.

**Comment by Rashidkallur** [comment]
Awesome, thanks!
