### ISSUE TITLE
Bug: Sessions in different time zones are different. 

### ISSUE THREAD

**Issue by ashwitag** [dayschedule/public-roadmap#30]
Clients booking sessions in the USA are not seeing the first available session, they are show options from second session onwards. 

As an example, 10am sessions on this page https://ashwita.dayschedule.com/online-healing show up if the time zone is calcutta, but in the US the earliest time available is 11.30am which is a problem because US clients need 10am slots. I am asking them to change time zone to book, but defeats the purpose and obviously only works if the client cross checks with me, otherwise no sessions get booked.

**Comment by vickyrathee** [comment]
This seems to happening for US, where date is changed to next/previous day.

For example 10am in India 27th May is actually 26th in US. So, we will make some changes to enable dates based on time-zone next week. 

![image](https://user-images.githubusercontent.com/6106479/170635466-7f0ccd5d-565e-4bb2-b08a-dd21579fc132.png)

**Comment by vickyrathee** [comment]
This is fixed on today's release.

https://dayschedule.com/docs/change-log
