### ISSUE TITLE
Upload file option during booking a meeting

### ISSUE THREAD

**Issue by anirudesharma** [dayschedule/public-roadmap#32]
We use dayschedule for consultancy services, if you can add upload file option during booking of the meeting, it will be very helpful as the user can upload their documents so we can read their documents and know what has to be done in the meeting.

**Comment by vickyrathee** [comment]
@anirudesharma The feature is already added by development and under testing, it will be released sometime next week or before 15th of June.

**Comment by vickyrathee** [comment]
@anirudesharma  File upload feature is released.

https://dayschedule.com/docs/change-log

![image](https://user-images.githubusercontent.com/6106479/172550622-6bc014fd-bbb4-498e-b158-f643024fdb5e.png)
