### ISSUE TITLE
Feature Request: Failed Payment Process

### ISSUE THREAD

**Issue by ashwitag** [dayschedule/public-roadmap#33]
Right now when payment fails after booking a session, 2 things are happening 
1. Client receives no email or intimation
2. My calendar gets booked anyway
So client tries again, cannot access previous slot, books another slot and then tries payment again. If they try 2-3 times, then 2-3 slots get booked, of which only one is paid for. My calendar in the meantime is getting booked with empty sessions. 

I'd like to request the following when payment fails -
1. Tentatively block the slot, and email the client that payment has failed, with link for payment. 
2. If no payment is made in 12 or 24 hours then the slot is released, with an email to client about it along with booking link. 
3. Not sure if this is possible, but if payment fails, can the payment portal send the client back to the dayschedule page to try payment again? I've seen this happen on some websites.

**Comment by doshisahil95** [comment]
Hi Team, what is the update on this feature request? I am having the same issue and its not helping me streamline my booking application. Thanks!

**Comment by vickyRathee** [comment]
@ashwitag @doshisahil95  Release confirmed: this is coming on 1st week of Jan

**Failed -**
- If payment failed(or no attempt made in next 2 minutes), an email will be sent to customer with payment link to retry within 15 minutes.

**Timeout** 
- If no payment received within 15 minutes, the booking will be canceled and the slot will be free to booked by next customer

**Comment by vickyRathee** [comment]
The failed payment processing has been implemented - https://dayschedule.com/docs/t/payment-integrations/300


![appointment booking payments flow](https://user-images.githubusercontent.com/6106479/212616487-05909dda-d155-4895-bc6c-2ef343b9936f.png)
