### ISSUE TITLE
Feature Request- passing parameters with variables

### ISSUE THREAD

**Issue by Lifeischoice** [dayschedule/public-roadmap#39]
Pre-populate invitee information on the scheduling page through passing variable  parameters to pre-populate calendar page For example first name, last name, dates, 
https://dayschedule.com/mycalendar?name= &email=, Etc. A Use case: a user completes a form on my site with name, email, etc and he’s redirected to my booking page with these information pre-populated on the schedule page. The user don’t need to complete same information multiple times.

**Comment by vickyrathee** [comment]
@Lifeischoice This feature is already available. Just pass the query parameter and it will work as expected.

Here is the working link with date, name and email I passed in URL - https://meet.dayschedule.com/product-demo?name=vikash&email=vikash.rathee@dayschedule.com&date=2022-06-07

![autfill-form-query-parameter](https://user-images.githubusercontent.com/6106479/172048791-5d47fa8d-e184-4ee2-af1b-9a4e2471f440.gif)

**Comment by Lifeischoice** [comment]
Awesome! Where can I find the list of variables to append?

**Comment by vickyrathee** [comment]
@Lifeischoice It's dynamic, you can pre-fill any question dynamically. Just use the `question=answer` in URL

**Multiple words question label -** 

Label: `Email address`, 
Query pram will be: `email=someone@gmail.com`

**Single word question label -** 
Label: `Name`
Query pram will be: `name=Nick`

**Another example**
Label: `Phone number`
Query pram will be: `phone=99999999`

![image](https://user-images.githubusercontent.com/6106479/172049416-2abc9d00-afb0-47aa-89a0-b229406de3a4.png)

**Comment by Lifeischoice** [comment]
Just for clarification: I currently have a form on my site and any user can
complete the form. On submit, the user is automatically redirected to my
booking page with the relevant information (name, email, answer to
questions) pre-populated on the booking form. Since there is no way of
knowing which user will  Fill the form out, how do I pass the info when
completed by a “random” user? What I am looking for are variable names for
example, name=first_name%20last_name&email=email&….this way, the variable
i.e. first_name will be replaced by actual first name of the user that
completed the form. Thanks

**Comment by vickyrathee** [comment]
As I mentioned, check your appointment form and pass the same question/answer to auto fill.
Obviously you know what question you have added in your registration form. So just add the answers of random user.

first=someone&last=someone&email=someone@gmail.com

**Comment by Lifeischoice** [comment]
Thank you for your response. I now understand. Will try it that way.

**Comment by Lifeischoice** [comment]
I have tried what you suggested and does not work. Please see this video and advice...thanks- https://www.loom.com/share/5eb0f9745bac4953b08fb4dd981425a2

**Comment by vickyrathee** [comment]
I see your videos and it's working fine. Whatever value is passed is pre-populated, just pass the correct values.

**Comment by Lifeischoice** [comment]
Thanks for your re-consideration. It is not working as expected...I currently use calendly and want to transition to dayschedule but not without this feature as it is key to booking consults on my website - this is how it is currently handled in calendly - https://help.calendly.com/hc/en-us/articles/360040257613-Information-you-can-send-in-the-redirect-URL

**Comment by vickyrathee** [comment]
See your dayschedule URL, the value passed is loaded correctly in registration form.

Here is screenshot from your video. So you are just passing the wrong value in **name**, instead of actual name.

![image](https://user-images.githubusercontent.com/6106479/172054229-b32ca53c-39cd-4399-803b-f01f151f9867.png)

**Comment by Lifeischoice** [comment]
Again thanks for your consideration and wanting to resolve this. You can test the results here - this is my website form based on calendly - https://mindbasic.com/call60 and this is the same form based on dayschedule https://www.mindbasic.com/day-schedule/.  You can confirm how the variables are passed in the calendly versiion. How can I setup dayschedule to work like the calendly version?

**Comment by vickyrathee** [comment]
Just send the correct value in dayschedule URL. 
I checked your website and you are not sending correct values in URL.

**Comment by Lifeischoice** [comment]
And that is what I have been asking? What variable (not hard coded) value should I add to the dayschedule url to make it work as the calendly version? Currently, dayschedule  just sends whatever value is “hard coded” in the form regardless of user input.  What variables do I need add to add to the form so that a random user’s inputs are sent to dayschedule? Please test both versions of the url I sent to see the difference.

**Comment by vickyrathee** [comment]
You should ask your developer to find out how to pass value from your website. 
We can help in DaySchedule only, and the dayschedule app is perfectly reading the values from the URL(sent by you) and setting it on the input boxes.

**Comment by Lifeischoice** [comment]
Thank you for confirming, finally that dayschedule do not currently have this calendly feature. Much appreciated.

**Comment by Lifeischoice** [comment]
I was able to figure it out and wanted to post here how I did it in case it helps others...I used elementor pro form but the process may also be available from othter form builders - https://www.loom.com/share/e0cbbbdeb73a4389a9e24fada8ee6f58
