### ISSUE TITLE
Ability to apply a workflow for multiple events

### ISSUE THREAD

**Issue by Lifeischoice** [dayschedule/public-roadmap#41]
It will be more efficient to able to apply the same workflow to multiple events. Currently, one has to create a workflow for each event. 
For example, I have created separate workflow reminders of  24 hr, 1 hr, 15 minutes before an event and workflow for webhook. These workflow has to be replicated for each event since I have similar workflow requirements for my events. For my use case, It will be more efficient if I can apply the 24 hr reminder to all selected events and the 1 hr reminder to all selected events etc. Another way is to be able to have multiple "triggers" for each workflows...(http://prntscr.com/7QtbEax6EVsD)

**Comment by vickyrathee** [comment]
The feature is has been added and scheduled to release on 7th July 2022

![image](https://user-images.githubusercontent.com/6106479/177270361-10691ea9-a1aa-47e7-85cb-412f372d789d.png)
