### ISSUE TITLE
Feature Request: Custom Signature

### ISSUE THREAD

**Issue by ashwitag** [dayschedule/public-roadmap#43]
Can we please have an option to include a customised signature at the end of every automated email? Rich text formation to include links etc. 

This way information that needs to go out to all customers can be easily included instead of having to go and create separate work flows for every event.

**Comment by vickyrathee** [comment]
@ashwitag The workflow feature has been improved and release is schedule for July, 7th. 
On the improved version, you'd be able to select all resources events/webinar etc. in single workflow and no need to create separate workflow for each event.

So this can be done using the single workflow re-designed coming on this Thursday.

![image](https://user-images.githubusercontent.com/6106479/177269795-789741d4-7e2c-44a0-9e0f-e0459134d5f7.png)

**Comment by vickyrathee** [comment]
Feature shipped to allow multi-select workflow - https://dayschedule.com/docs/change-log
