### ISSUE TITLE
Custom Duration Feature

### ISSUE THREAD

**Issue by krisselberg** [dayschedule/public-roadmap#44]
I am implementing a room scheduler for my website and a feature to allow users to reserve a room for a custom duration (up to a maximum time limit) would help a lot.

**Comment by vickyRathee** [comment]
This is coming on 1st week of Jan.

**Comment by vickyRathee** [comment]
This feature is released now - https://dayschedule.com/docs/change-log

Video - https://www.youtube.com/watch?v=Uq3Kr_dndLI
