### ISSUE TITLE
Provide option of "Show available start times in increments of"

### ISSUE THREAD

**Issue by Ssazwal** [dayschedule/public-roadmap#48]
This feature allows for more start times to be included and the calendar bookings to be more flexible and accomodating. Right now, it calculates start times according to work schedule and event length plus break time, but because of that relevant options that can be provided to clients are getting missed out. 
e.g. Dayschedule shows only 2 options for a particular date synced to my calendar : 11:15, 2:15 as follows:
![image](https://user-images.githubusercontent.com/112922017/188595834-666794ff-c9f7-43d5-b67f-ed3782c0f4d3.png)

However for the same date and calendar sync, same options, calendly allows following times to show: 11:15, 1:45, 2, 2:15
![image](https://user-images.githubusercontent.com/112922017/188596193-9435cae4-fc2c-4976-b7e5-3d65db1515a7.png)

This is because of the option for start times in increment of, when I select 15 mins, it shows start times in increment of 15 mins instead of deciding the increments itself. This is an example of this option on calendly for reference
![image](https://user-images.githubusercontent.com/112922017/188594994-770ea3f3-ca7c-49f7-a15e-98894ee1d7b3.png)

**Comment by vickyRathee** [comment]
This feature has been added now.

![appointment slots increment of](https://user-images.githubusercontent.com/6106479/230890358-c99aa4bd-0123-4b3d-9bbf-f8de9135c165.png)
