### ISSUE TITLE
Focus on Type of Meeting with its name first, for clear mobile calendar view

### ISSUE THREAD

**Issue by Bjorn77Karlsson** [dayschedule/public-roadmap#53]
In TidyCal focus in calendar is on the meeting and what kind of meeting it is. But in DaySchedule focus is on other things that I take for granted when it is in calendar (Booking confirmed: Name - 2022-10-17 (GMT +02.00)) in total 44 letter + name of attendee, leaving no space for what kind of meeting it is or what it is about, this is a BIG problem especially on mobile devices where the view always is limited. Would be so much better to have that "not so important information" after meeting name. 
When having many different meetings the DaySchedule view will make it really hard to keep track of what each meeting is about without having to open up each meeting. This is not sustainable for a full calendar with appointments, especially for people like me and most others as well who use their mobile daily to get a vew over their calendar.
![Dayshedule calendar improvment](https://user-images.githubusercontent.com/70579206/196038496-00dfe89e-3b9a-4391-abda-d9e5ffef3b2c.PNG)

**Comment by vickyRathee** [comment]
This has been fixed to display event name in this format -  `${invitee.name}: ${event.name}` as discussed on #21
