### ISSUE TITLE
Swedish flag is wrong

### ISSUE THREAD

**Issue by gitpet** [dayschedule/public-roadmap#55]
Hi, I would like you to please provide Swedish language option, because I will be using Dayschedule a lot for the Swedish market.

Edit:
I just noticed that you do have Swedish, but the flag is incorrect, which makes it easy to miss.

All the best,
Peter

**Comment by vickyRathee** [comment]
@gitpet Swedish is already available in [dayschedule.com](https://dayschedule.com) appointment scheduler.

![image](https://user-images.githubusercontent.com/6106479/200732877-c65016c1-cf0e-42ab-9df5-a772b9ad6c6f.png)
