### ISSUE TITLE
Translation & Language Contribution

### ISSUE THREAD

**Issue by vickyRathee** [dayschedule/public-roadmap#56]
Hi DaySchedule Community Members,

We are looking for some help in local language translation for better language experience on appointments. We'll be happy to add a 50% discount for 3 months to any contributor who provide translation in below format in any international language they wish to add in [dayschedule.com](https://dayschedule.com) 

For example, here is the translation file for Germán. (code: `de`)

1. Copy the JSON from below frame
2. Write or correct the translation for each key ".."
3. Submit in comment below

```
{
  "calendar": {
    "title": "Select a Date & Time",
    "weekday": {
      "Mon": "Mon",
      "Tue": "Tue",
      "Wed": "Wed",
      "Thu": "Thu",
      "Fri": "Fri",
      "Sat": "Sat",
      "Sun": "Sun"
    },
    "month": {
      "January": "January",
      "February": "February",
      "March": "March",
      "April": "April",
      "May": "May",
      "June": "June",
      "July": "July",
      "August": "August",
      "September": "September",
      "October": "October",
      "November": "November",
      "December": "December"
    }
  },
  "button": {
    "Confirm booking": "Confirm booking",
    "Pay and confirm": "Pay and confirm",
    "Cancel": "Cancel",
    "Add guests": "Add guests",
    "Cancel booking": "Cancel booking"
  },
  "label": {
    "Registration": "Registration",
    "Guest email addresses": "Guest email addresses",
    "Maximum allowed": "Maximum allowed",
    "One email per line, or comma separated": "One email per line, or comma separated",
    "Booking confirmed": "Booking confirmed",
    "Your booking is confirmed": "Your booking is confirmed",
    "Add to calendar": "Add to calendar",
    "Download iCal": "Download iCal",
    "This field is required": "This field is required",
    "Date": "Date",
    "Name": "Name",
    "Reschedule reason": "Reschedule reason",
    "Cancel reason": "Cancel reason",
    "Price options": "Price options",
    "Payment gateway": "Payment gateway",
    "Location": "Location",
    "Retry payment": "Retry payment"
  },
  "question": {
    "Name": "Your name",
    "Email address": "Your email address"
  }
}

```

**Comment by su-me-ben** [comment]
@vickyRathee: "Registration" I loosely translated as "Your contact details". "Name" and "Email Address" I translated accordingly with "Your Name" and "Your Email Address".
I thought that this way it sounds less like you are registering for a webapp or something similar, which might scare off some users. 

{
  "calendar": {
    "title": "Bitte wählen Sie ein Datum und eine Uhrzeit aus",
    "weekday": {
      "Mon": "Mon",
      "Tue": "Die",
      "Wed": "Mit",
      "Thu": "Don",
      "Fri": "Fre",
      "Sat": "Sam",
      "Sun": "Son"
    },
    "month": {
      "January": "Januar",
      "February": "Februar",
      "March": "März",
      "April": "April",
      "May": "Mai",
      "June": "Juni",
      "July": "Juli",
      "August": "August",
      "September": "September",
      "October": "Oktober",
      "November": "November",
      "December": "Dezember"
    }
  },
  "button": {
    "Confirm booking": "Buchung bestätigen",
    "Cancel": "Abbrechen"
    "Add guests": "Gäste hinzufügen"
  }
  "label" : {
    "Registration": "Ihre Kontaktdaten"
    "Guest email(s)" : "Gast-E-Mail-Adresse(n)" 
    "Add up to 10 guests email address(s) to join this event" : "Fügen Sie die E-Mail-Adressen von bis zu 10 Gäste hinzu, die an diesem Termin teilnehmen sollen",
    "Booking confirmed": "Buchung bestätigt",
    "Your booking is confirmed": "Ihre Buchung wurde bestätigt",
    "Add to calendar": "Zum Kalender hinzufügen",
    "Download iCal": "iCal-Datei herunterladen",
    "This field is required" : "Die ist ein Pflichtfeld"  
    "Date" : "Datum",
    "Name": "Name"
  }
  "question": {
    "Name": "Ihr Name",
    "Email address": "Ihre E-Mail-Addresse"
  }
}

**Comment by joshuabeukers** [comment]
@vickyRathee also missing the 'Book now' translation option. Could you translate it to 'Afspraak maken'?

**Comment by vickyRathee** [comment]
Received on email from Wilman, Spanish contributor

```
{
  "calendar": {
    "title": "Escoja fecha y hora",
    "dias laborables": {
      "Mon": "Lun",
      "Tue": "Mar",
      "Wed": "Mie",
      "Thu": "Jue",
      "Fri": "Vie",
      "Sat": "Sab",
      "Sun": "Dom"
    },
    "month": {
      "January": "Enero",
      "February": "Febrero",
      "March": "Marzo",
      "April": "Abril",
      "May": "Mayo",
      "June": "Junio",
      "July": "Julio",
      "August": "Agosto",
      "September": "Septiembre",
      "October": "Octubre",
      "November": "Noviembre",
      "December": "Diciembre"
    }
  },
  "button": {
    "Confirm booking": "Confirmar reserva",
    "Cancel": "cancelar"
    "Add guests": "Agregar invitados"
  }
  "label" : {
    "Registration": "Registrarse"
    "Guest email(s)" : "email"
    "Add up to 10 guests email address(s) to join this event" : "Agregue hasta 10 direcciones de correo electrónico de invitados para unirse a este evento",
    "Booking confirmed": "Confirmar reserva",
    "Your booking is confirmed": "Su reserva fue confirmada",
    "Add to calendar": "Añadir al calendario",
    "Download iCal": "Descargar iCal",
    "This field is required" : "Este parametro es obligatorio"  
    "Date" : "Fecha",
    "Name": "Nombre"
  }
  "question": {
    "Name": "Nombre",
    "Email address": "Correo electrónico"
  }
} 
```

**Comment by Wilmancel** [comment]
Gracias y espero poder seguir colaborando ...exitos

**Comment by aikiarro** [comment]
Wuhuuu, ESTONIAN translation is coming up: 

{
  "calendar": {
    "title": "Vali sobiv kuupäev ja kellaaeg",
    "weekday": {
      "Mon": "E",
      "Tue": "T",
      "Wed": "K",
      "Thu": "N",
      "Fri": "R",
      "Sat": "L",
      "Sun": "P"
    },
    "month": {
      "January": "Jaanuar",
      "February": "Veebruar",
      "March": "Märts",
      "April": "Aprill",
      "May": "Mai",
      "June": "Juuni",
      "July": "Juuli",
      "August": "August",
      "September": "September",
      "October": "Oktoober",
      "November": "November",
      "December": "Detsember"
    }
  },
  "button": {
    "Confirm booking": "Kinnita",
    "Cancel": "Tühista"
    "Add guests": "Lisa külalisi"
  }
  "label" : {
    "Registration": "Sisesta kohtumiseks vajalikud detailid"
    "Guest email(s)" : "Külaliste e-mailid" 
    "Add up to 10 guests email address(s) to join this event" : "Lisa kuni 10 külalise emaili aadressi",
    "Booking confirmed": "Kohtumine kinnitatud",
    "Your booking is confirmed": "Sinu kohtumine on kinnitatud",
    "Add to calendar": "Lisa kalendrisse",
    "Download iCal": "Laadi iCal",
    "This field is required" : "See väli on nõutud"  
    "Date" : "Kuupäev",
    "Name": "Nimi"
  }
  "question": {
    "Name": "Nimi",
    "Email address": "Emaili aadress"
  }
}

**Comment by vickyRathee** [comment]
The custom translation feature is now available in DaySchedule, so need need to provide translation to add in backend. Customer can go to settings > [translation to localize their appointment booking system](https://dayschedule.com/docs/t/how-to-translate-your-appointment-booking-pages-into-multiple-languages/390).

![appointment booking system translation](https://github.com/dayschedule/public-roadmap/assets/6106479/2fa541f6-0871-4842-a985-2a8365340dea)
