### ISSUE TITLE
New Feature Request: Rearrange Events on pages

### ISSUE THREAD

**Issue by ashwitag** [dayschedule/public-roadmap#57]
Please provide the option to rearrange the events on the pages. Either drag and drop or even arrow to shift up and down is great. Need to be able to arrage the events in the appropriate order.

**Comment by vickyRathee** [comment]
@ashwitag  This feature has been released, you may re-arrange your events now on [dayschedule.com](https://dayschedule.com/)

![image](https://user-images.githubusercontent.com/6106479/204979402-00230e5c-61dd-48ae-943a-164400545c50.png)
