### ISSUE TITLE
Feature request: Custom Location

### ISSUE THREAD

**Issue by hvbasesloaded** [dayschedule/public-roadmap#63]
It gets old having to type in the same address information over and over again every time I am creating a new service. We don't have online anything, except booking. Would be nice to just select the location each time.

**Comment by vickyRathee** [comment]
You can use the "Make a copy" feature in resource. It will copy everything: name, address etc... and you can change values only needed in the copied resource.

**Comment by hvbasesloaded** [comment]
Thanks - missed that!
