### ISSUE TITLE
Facebook Pixel issue

### ISSUE THREAD

**Issue by WeightlossCoach** [dayschedule/public-roadmap#68]
Hi Team, Hope you all doing Good. Please add the Facebook meta tag in website so I can verify the domain in Facebook ad. It's very important feature to run and track the conversion. 

Please add or resolve this issue asap.. 
![image](https://user-images.githubusercontent.com/131256343/233046060-03eff73d-7c25-43cf-ab69-a64733d34b8a.png)

**Comment by vickyRathee** [comment]
The dayschedule pages are JavaScript generated and it won't work as mentioned in step 2 `verification will fail if meta-tag is loaded dynamically by JavaScript`. So, it won't work.

Solution: Add the pixel on your website `/thank-you` page and use the redirect feature to redirect when the booking is confirmed.

https://dayschedule.com/docs/t/how-to-show-custom-thank-you-message-redirect-to-website-after-appointment-confirmed/379#_Redirect_to_website

**Comment by WeightlossCoach** [comment]
Then u guys need to remove that Google analytics & Facebook pixel option mentioned in Integration. So it will give better clarity to one who buys the app.. 

I bought this particularly for this reason only ..

Thanks for the feedback ..

**Comment by vickyRathee** [comment]
We will find a solution in long term. Right now it's not possible and limitation in on FB side. Hopefully, they will remove this condition as more and more JS based product revolution is coming like React, Angular and Vue applications.

If not, we will implement something to get this verified.
