### ISSUE TITLE
Booking notification via text message

### ISSUE THREAD

**Issue by Happyjoy5** [dayschedule/public-roadmap#70]
I am currently unable to receive booking conformations via text messages and only through email. This is a hinderance as it would be convenient to receive a text stating a new appointment has been made vs in an email.

**Comment by vickyRathee** [comment]
The SMS feature is already available.
Contact support to share your number and plan details, if you need any help -  https://dayschedule.com/contact

**Comment by Happyjoy5** [comment]
Can ypu please explain toe what I am doing wrong and how this can be fixed
 This is truly a deal breaker as this is how I receive immediate
notifications.
