### ISSUE TITLE
Sending workflow E-mail through professional e-mail id from your own domain.

### ISSUE THREAD

**Issue by yashgupta1131** [dayschedule/public-roadmap#72]
It will give proper branding to e-mails to customers.

**Comment by vickyRathee** [comment]
The gmail integration feature is now available to send email from Business/Personal email address.
 https://dayschedule.com/docs/t/how-to-send-automated-appointment-reminders-from-gmail/398
![image](https://github.com/dayschedule/public-roadmap/assets/6106479/b00c1a33-bdcf-40a8-8701-29a1efc2436b)
