### ISSUE TITLE
Priority One: In Workflow if the date & time is passed for that workflow, you should skip those reminders. But currently Ex: if let's say someone scheduled the call within 3 hrs of actual call time & in workflow we set reminder for 1 day, 6 hr, 12 hrs before scheduled event, dayschedule triggers all previous workflows at once which should in reality be skipped.

### ISSUE THREAD

**Issue by yashgupta1131** [dayschedule/public-roadmap#73]
So customer gets 3 mails, 3 whatsapp messages & 3 sms all together, which is bad.

**Comment by vickyRathee** [comment]
Most probably you've 3 workflow created for same event. Check your workflow or contact: support@dayschedule.com

**Comment by yashgupta1131** [comment]
In single workflow I am not seeing option to schedule multiple reminders for different times. Am I missing anything here.
Because then I'll have to create multiple workflow for different times to differently timed reminders.
