### ISSUE TITLE
Bug: Workflow Trigger Issue

### ISSUE THREAD

**Issue by yashgupta1131** [dayschedule/public-roadmap#75]
Ideally any workflow should not trigger if it doesn't meet the condition.
If workflow condition is 1 day before the event starts & someone books session 6 hours before the event. This workflow should not be triggered at all because it doesn't meet the criteria of 1 day before event.

Any mail campaign we run & we say in it, 1 day is left for the session. This mail will also get triggered at the time of event booking itself. It fails our mail reminder campaigns.

**Comment by vickyRathee** [comment]
Bug confirmed, will be fixed by Friday 10/13.

**Comment by vickyRathee** [comment]
This has been fixed.
