### ISSUE TITLE
Bug: * *  Two Star signs are appearing in booking page description, although they are not added to description.

### ISSUE THREAD

**Issue by yashgupta1131** [dayschedule/public-roadmap#76]
Please refer screenshots below

![Screenshot (1043)](https://github.com/dayschedule/public-roadmap/assets/144734797/f1fffd63-7882-400c-ac9d-5c997b8484d8)
![Screenshot (1044)](https://github.com/dayschedule/public-roadmap/assets/144734797/a2252c64-bdd9-49c7-8130-b5d447eacd22).

**Comment by vickyRathee** [comment]
Delete and re-write the description.
