### ISSUE TITLE
Bug: Bullet point numbering bug in description

### ISSUE THREAD

**Issue by yashgupta1131** [dayschedule/public-roadmap#77]
How to Replicate.
1. Create event with description with 3 numbered bullet point. (Bullet point numbering will automatically be 1, 2, & 3).
2. Save the event.
3. Edit the event, go to description page, don't change anything, move, next, next, event is saved, now open the event page. Now the bullet point numbers are replaced with 3, 4, & 5 instead of 1, 2 & 3.  & when you'll edit the event & go to description page, you'll find bullet point numbers automatically updated to 3, 4, & 5. 

![Uploading Screenshot (1042).png…]()

**Comment by yashgupta1131** [comment]
![Screenshot (1042)](https://github.com/dayschedule/public-roadmap/assets/144734797/c4795ce5-e7a1-4cb8-949f-ea6cce420f07)

**Comment by vickyRathee** [comment]
Click on bullet point button to reset or re-write the description again.

**Comment by yashgupta1131** [comment]
It's still not working, issue is every time we go & make any change in the schedule & save the event. The event description number automatically changes. & Everytime we have to reset the bullet points again & again which is a little frustrating. @vickyRathee
