### ISSUE TITLE
Bug: In-line code adding to Website: mobile layout issue

### ISSUE THREAD

**Issue by yashgupta1131** [dayschedule/public-roadmap#78]
In mobile: Event Description layout is not coming properly.  
In small mobile screen, if all the text appears only on half right hand side screen, it looks terrible & ends of consuming a lot of screen.

When we add In-Line/popup code to webpage to show dayschedule.

![WhatsApp Image 2023-10-11 at 4 51 53 AM](https://github.com/dayschedule/public-roadmap/assets/144734797/27407918-8038-49d7-9578-2283a287e84d)

**Comment by yashgupta1131** [comment]
In small mobile screen, if all the text appears only on half right hand side screen, it looks terrible & ends of consuming a lot of screen.

**Comment by vickyRathee** [comment]
Use the [latest version of widget](https://www.npmjs.com/package/dayschedule-widget), the long descriptions is truncated automatically.

![image](https://github.com/dayschedule/public-roadmap/assets/6106479/f70cc5a7-52c2-4b05-82fc-9e1b08b2cef3)
