### ISSUE TITLE
Feature Request: Back Button on Event page

### ISSUE THREAD

**Issue by yashgupta1131** [dayschedule/public-roadmap#79]
In Event page, people are able to see back button, upon clicking it, they can see all of our calendars.
In case if we don't want them to see rest of our calendars, we should have the option to prevent them from going back and seeing all of our open calendars.

**Comment by vickyRathee** [comment]
You may hide the complete header including back button on your appointment page.

```
hideHeader: true
```

See example here - https://dayschedule.com/widget

```
daySchedule.initPopupWidget({
    url: 'https://meet.dayschedule.com/product-demo',
    hideHeader: true
});
```
