### ISSUE TITLE
Bug: Mobile Layout Problem - Using Inline/popup code in Website: Even on new Code

### ISSUE THREAD

**Issue by yashgupta1131** [dayschedule/public-roadmap#81]
URL Link: https://10xproductivitysecrets.com/?page_id=474

Code Using: "[dayschedule url="https://yashgupta.dayschedule.com/entrepreneurs-productivity-session-1" type="inline"]"

Below is the screenshot on mobile, description text is still coming in half screen only.
![WhatsApp Image 2023-10-16 at 3 50 20 AM](https://github.com/dayschedule/public-roadmap/assets/144734797/08c1ce88-b57f-4904-9844-ba451ed16d0a)

I have also tried using the below code within < > brackets. 
dayschedule-widget url="https://yashgupta.dayschedule.com/entrepreneurs-productivity-session-1"></dayschedule-widget
But with this code layout is getting messed up on both pc & mobile.

It's important for fb lead tracking, as we can add pexel on our page with day schedule widget. Since the widget layout is not conducive for mobile, it's not possible to use at the moment

**Comment by vickyRathee** [comment]
A new version of wordpress plugin coming soon

**Comment by vickyRathee** [comment]
This was fixed in wordpress version 1.0, please update your plugin. 

https://wordpress.org/plugins/dayschedule-appointment-event-and-service-booking/
