### ISSUE TITLE
Flexibility on forms such as rename option, different location...etc

### ISSUE THREAD

**Issue by penyGH** [dayschedule/public-roadmap#82]
💡 Say Hi on website chat to ask general questions, the chatbox is available on https://dayschedule.com/pricing and admin panel after login. Remember, this is not a support forum and you'd need to https://dayschedule.com/contact for general support.

**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is to provide full details.

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by vickyRathee** [comment]
Full form customization is now released including first name, last name, optional email etc.

https://dayschedule.com/docs/t/how-to-customize-the-appointment-registration-form/383
