### ISSUE TITLE
BUG: Upon Editing dayschedule resource, the numbered bullet list in description is getting auto edited to new numbered.

### ISSUE THREAD

**Issue by yashgupta1131** [dayschedule/public-roadmap#83]
Upon Editing dayschedule resource, the numbered bullet list in description of resource is getting auto edited to new numbered.
Every time you make a new change in calendar, the numbered list in description will be automatically updated to new numbers.

**Comment by vickyRathee** [comment]
Upstream library issue, can't be fixed. 

Please clear the editor or click on bullet point button to refresh the list numbering.
