### ISSUE TITLE
Feature Request: A code I can provide a client to avail discount.

### ISSUE THREAD

**Issue by puneetagrawalils** [dayschedule/public-roadmap#86]
Hi,

Is your feature request related to a problem? Please describe.
I would like to provide a code to clients so they can avail a discount for a certain number of appointments.

Describe the solution you'd like
Add a feature for discounts.

Describe alternatives you've considered
I created a separate private resource with lowered price. But it is cumbersome to ask clients to book appointments through different links.

**Comment by vickyRathee** [comment]
Add the code to your Stripe, [Razorpay payment gateway](https://dayschedule.com/docs/t/how-to-use-razorpay-payment-for-appointment-bookings/312) and provide to the client. DaySchedule just redirect to selected payment gateway, so any payment gateway which supports coupon will work for you.

https://www.youtube.com/watch?v=BjCXhTnhm_I
