### ISSUE TITLE
Send WhatsApp messages by a Google Calendar integration

### ISSUE THREAD

**Issue by Giukas76** [dayschedule/public-roadmap#87]
I need to send WhatsApp messages automatically through a job that reads my events/appointments from Google Calendar, recognizes the recipient's phone number, and sends them a message with pre-written text.
Example: In Google Calendar, I have an event like this:
Rita Facca [event name]
3934567899 lorem ipsum dolor sit amet [event description]
lavender [event color]

The workflow triggers every day at 8 AM and reads all my events for the day.
If it finds one with the configuration described above, it extracts the phone number and sends a WhatsApp message with standard text.

Similarly, it will send another message if it finds an event with the same format but a different Google color.

I do not need to publish my calendar.

Thank you!

**Comment by vickyRathee** [comment]
This is not planned unfortunately, only appointment taken on dayschedule will receive reminders and notifications
