### ISSUE TITLE
Feature Request: Ability to trigger webhook [x] minutes before an event ends

### ISSUE THREAD

**Issue by AslanGoldenhour** [dayschedule/public-roadmap#91]
**Is your feature request related to a problem? Please describe.**
Our company uses scheduling for property inspections, which sometimes run long. We want to avoid situations where people's calendars are technically available, while in reality they are still on a long-running inspection and not available. If we had a webhook notification 15 minutes before ends, then we could implement custom business logic to auto-extend long-running events.

**Describe the solution you'd like**
We like to specify a webhook 15 minutes BEFORE an event ends. Right now the only option is to set some amount of time after an event ends.

**Describe alternatives you've considered**
Manually extending event durations if they are running long.

**Additional context**
<img width="1112" alt="Screenshot 2024-10-27 at 11 03 34 PM" src="https://github.com/user-attachments/assets/f8c9ffd8-63b0-45a2-b60c-9adf68455c58">

**Comment by vickyRathee** [comment]
This is not planned, please use `event_start` to trigger after 15 minutes...

So, let's say your booking is for 30 minutes. Setting up a webhook after 15 minutes of event_start is same as setting up a webhook using before 15 minutes of event_end.
